services:
  - type: web
    name: blade-stickers
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn blade_stickers.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"

