# Generated by Django 6.0.7 on 2026-08-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Blade Stickers', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Website Brand Logo', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Browser Favicon Icon', null=True, upload_to='site/')),
                ('hero_title', models.CharField(default='Custom Stickers & Wall Art Crafted to Elevate Your Style', max_length=200)),
                ('hero_subtitle', models.TextField(default='Express your personality with high-definition, waterproof vinyl stickers, anime decals, Ethiopian artist posters, and sleek room decorations.')),
                ('about_story', models.TextField(default='Blade Stickers was founded with a single passion: creating high-durability, vivid visual art that transforms everyday objects into personal canvas expressions. From laptop decals to massive wall posters, we print with ultra-sharp detail.')),
                ('about_mission', models.TextField(default='To deliver premium quality die-cut stickers and posters across Ethiopia and internationally, empowering artists, music lovers, and aesthetic enthusiasts.')),
                ('stats_stickers_count', models.IntegerField(default=15000, help_text='Stickers printed count')),
                ('stats_customers_count', models.IntegerField(default=3500, help_text='Happy customers count')),
                ('stats_designs_count', models.IntegerField(default=450, help_text='Custom designs catalog count')),
                ('stats_rating', models.CharField(default='4.9 ★', help_text='Satisfaction rating label', max_length=10)),
                ('phone_number', models.CharField(default='+251 91 234 5678', max_length=50)),
                ('telegram_username', models.CharField(default='bladestickers', help_text='Telegram username without @', max_length=100)),
                ('whatsapp_number', models.CharField(default='251912345678', help_text='WhatsApp phone number with country code', max_length=50)),
                ('tiktok_handle', models.CharField(default='@bladestickers', help_text='TikTok handle', max_length=100)),
                ('instagram_handle', models.CharField(default='@bladestickers', help_text='Instagram handle', max_length=100)),
                ('facebook_link', models.URLField(blank=True, default='https://facebook.com')),
                ('email', models.EmailField(default='contact@bladestickers.com', max_length=254)),
                ('address', models.CharField(default='Bole, Addis Ababa, Ethiopia', max_length=255)),
                ('map_embed_url', models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d126107.03986877085!2d38.70014264335936!3d9.006001200000003!2m3!1f0!1f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x164b85cef5ab402d%3A0x8467b6b037a24d49!2sAddis%20Ababa!5e0!3m2!1sen!2set!4v1700000000000!5m2!1sen!2set')),
                ('footer_text', models.TextField(default='© 2026 Blade Stickers. High precision die-cut stickers, anime decals, Ethiopian musician posters, and custom wall art.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, help_text='e.g. Graphic Designer, Anime Fan, DJ', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('message', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Star rating from 1 to 5')),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['ordering', '-created_at'],
            },
        ),
    ]
